---
groups:
  - name: custom_rules
    rules:
    - record: path:http_requests_total:sum
      expr: sum(http_requests_total)

    - record: path:http_requests_total:failure_procent
      expr: sum(http_requests_total{status='500'}) / sum(http_requests_total{status!='500'}) * 100
